Data replication source servers on prem
Cloudyeli/capci_group2 pull request #4
Opened 2022-12-13 10:35 UTC by mikomeller

on-prem data centre was already deployed and vpc can be used.
@Cloudyeli it makes sense for you to review the code as you will work with the vpc to create VPC pairing.

2022-12-13 12:39 UTC, Cloudyeli approved these changes
The userdata I cant review, because I am not in it, but everthing else seems good :)

2022-12-13 14:57 UTC, Jeena-J requested changes
Added some inline comments. Mostly related to naming conventions. Please refer [best practices](https://www.terraform-best-practices.com/naming)

2022-12-13 14:57 UTC, Jeena-J commented on OnPremInfra/provider.tf
> +}
terraform version needs to be specified so that we can lock the configuration to a specific terraform version. Refer to https://developer.hashicorp.com/terraform/tutorials/configuration-language/provider-versioning. Use the first method specified.

2022-12-16 09:11 UTC, mikomeller commented on OnPremInfra/terraform.tfvars
> +# private_subnet_name = "private_subnet_database"
done

2022-12-16 09:11 UTC, mikomeller commented on OnPremInfra/output.tf
> +# }
done

2022-12-16 09:11 UTC, mikomeller commented on OnPremInfra/routing_tables.tf
> +    Name = "privateRT"
done

2022-12-16 09:12 UTC, mikomeller commented on OnPremInfra/provider.tf
> +}
done

2022-12-16 10:15 UTC, mikomeller reviewed
please review and merge

2022-12-19 09:24 UTC, Jeena-J approved these changes

2022-12-19 09:31 UTC, merged