Initialise aws mgn service in frankfurt region
Cloudyeli/capci_group2 pull request #5
Opened 2022-12-13 11:30 UTC by Cloudyeli

Migration VPC and Subnets are created. VPC Peering is in its own folder.

2022-12-13 16:37 UTC, Jeena-J requested changes

2022-12-13 16:37 UTC, Jeena-J commented on new_network/VPC_Peering/vpc_peering.tf
> +  # peer_owner_id = var.peer_owner_id ### uses by default the owner ID of Owner Account
remove commented code if not required.

2022-12-13 16:39 UTC, Jeena-J commented
Minor changes. 
- Apply terraform fmt command on all files. 
- add the tf lock file to .gitignore file so that they dont get included in the commit.

Please check the inline comments as well.

2022-12-13 16:42 UTC, Jeena-J commented
Reopening accidentally closed PR

2022-12-13 17:24 UTC, Sadafpara approved these changes
Looks good to me!

2022-12-15 10:45 UTC, Sadafpara commented
There is an unresolved conflict

2022-12-19 09:25 UTC, Jeena-J approved these changes

2022-12-19 10:30 UTC, merged